
package com.businesslogic.goal.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusinessLogicGoal", targetNamespace = "http://ws.goal.businesslogic.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BusinessLogicGoal {


    /**
     * 
     * @param accessToken
     * @param userId
     * @param personId
     * @param steps
     * @param diffGoal
     * @param refresh
     * @param diffSteps
     * @param lifeStyle
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeStepsControl")
    @WebResult(name = "sentenceSteps", targetNamespace = "")
    @RequestWrapper(localName = "ChangeStepsControl", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeStepsControl")
    @ResponseWrapper(localName = "ChangeStepsControlResponse", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeStepsControlResponse")
    @Action(input = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeStepsControlRequest", output = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeStepsControlResponse")
    public String changeStepsControl(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh,
        @WebParam(name = "diffGoal", targetNamespace = "")
        int diffGoal,
        @WebParam(name = "lifeStyle", targetNamespace = "")
        String lifeStyle,
        @WebParam(name = "diffSteps", targetNamespace = "")
        int diffSteps,
        @WebParam(name = "steps", targetNamespace = "")
        int steps);

    /**
     * 
     * @param diffCalories
     * @param accessToken
     * @param userId
     * @param calories
     * @param personId
     * @param diffGoal
     * @param refresh
     * @param lifeStyle
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeCaloriesControl")
    @WebResult(name = "sentenceCalories", targetNamespace = "")
    @RequestWrapper(localName = "ChangeCaloriesControl", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeCaloriesControl")
    @ResponseWrapper(localName = "ChangeCaloriesControlResponse", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeCaloriesControlResponse")
    @Action(input = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeCaloriesControlRequest", output = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeCaloriesControlResponse")
    public String changeCaloriesControl(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh,
        @WebParam(name = "diffGoal", targetNamespace = "")
        int diffGoal,
        @WebParam(name = "lifeStyle", targetNamespace = "")
        String lifeStyle,
        @WebParam(name = "diffCalories", targetNamespace = "")
        int diffCalories,
        @WebParam(name = "calories", targetNamespace = "")
        int calories);

    /**
     * 
     * @param distance
     * @param diffDistance
     * @param accessToken
     * @param userId
     * @param personId
     * @param diffGoal
     * @param refresh
     * @param lifeStyle
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeDistanceControl")
    @WebResult(name = "sentenceDistance", targetNamespace = "")
    @RequestWrapper(localName = "ChangeDistanceControl", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeDistanceControl")
    @ResponseWrapper(localName = "ChangeDistanceControlResponse", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeDistanceControlResponse")
    @Action(input = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeDistanceControlRequest", output = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeDistanceControlResponse")
    public String changeDistanceControl(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh,
        @WebParam(name = "diffGoal", targetNamespace = "")
        int diffGoal,
        @WebParam(name = "lifeStyle", targetNamespace = "")
        String lifeStyle,
        @WebParam(name = "diffDistance", targetNamespace = "")
        double diffDistance,
        @WebParam(name = "distance", targetNamespace = "")
        double distance);

    /**
     * 
     * @param accessToken
     * @param startWeight
     * @param status
     * @param userId
     * @param personId
     * @param refresh
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeWeightControl")
    @WebResult(name = "sentenceWeight", targetNamespace = "")
    @RequestWrapper(localName = "ChangeWeightControl", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeWeightControl")
    @ResponseWrapper(localName = "ChangeWeightControlResponse", targetNamespace = "http://ws.goal.businesslogic.com/", className = "com.businesslogic.goal.ws.ChangeWeightControlResponse")
    @Action(input = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeWeightControlRequest", output = "http://ws.goal.businesslogic.com/BusinessLogicGoal/ChangeWeightControlResponse")
    public String changeWeightControl(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "startWeight", targetNamespace = "")
        double startWeight);

}
