
package com.businesslogic.goal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "businessLogicServiceGoal", targetNamespace = "http://ws.goal.businesslogic.com/", wsdlLocation = "https://businesslogicservicegoal.herokuapp.com/ws/businessLogicServiceGoal?wsdl")
public class BusinessLogicServiceGoal
    extends Service
{

    private final static URL BUSINESSLOGICSERVICEGOAL_WSDL_LOCATION;
    private final static WebServiceException BUSINESSLOGICSERVICEGOAL_EXCEPTION;
    private final static QName BUSINESSLOGICSERVICEGOAL_QNAME = new QName("http://ws.goal.businesslogic.com/", "businessLogicServiceGoal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://businesslogicservicegoal.herokuapp.com/ws/businessLogicServiceGoal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSLOGICSERVICEGOAL_WSDL_LOCATION = url;
        BUSINESSLOGICSERVICEGOAL_EXCEPTION = e;
    }

    public BusinessLogicServiceGoal() {
        super(__getWsdlLocation(), BUSINESSLOGICSERVICEGOAL_QNAME);
    }

    public BusinessLogicServiceGoal(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSINESSLOGICSERVICEGOAL_QNAME, features);
    }

    public BusinessLogicServiceGoal(URL wsdlLocation) {
        super(wsdlLocation, BUSINESSLOGICSERVICEGOAL_QNAME);
    }

    public BusinessLogicServiceGoal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSINESSLOGICSERVICEGOAL_QNAME, features);
    }

    public BusinessLogicServiceGoal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessLogicServiceGoal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusinessLogicGoal
     */
    @WebEndpoint(name = "BusinessLogicGoalImplPort")
    public BusinessLogicGoal getBusinessLogicGoalImplPort() {
        return super.getPort(new QName("http://ws.goal.businesslogic.com/", "BusinessLogicGoalImplPort"), BusinessLogicGoal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessLogicGoal
     */
    @WebEndpoint(name = "BusinessLogicGoalImplPort")
    public BusinessLogicGoal getBusinessLogicGoalImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.goal.businesslogic.com/", "BusinessLogicGoalImplPort"), BusinessLogicGoal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSLOGICSERVICEGOAL_EXCEPTION!= null) {
            throw BUSINESSLOGICSERVICEGOAL_EXCEPTION;
        }
        return BUSINESSLOGICSERVICEGOAL_WSDL_LOCATION;
    }

}
