
package com.storageservice.person.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "storageServicePerson", targetNamespace = "http://ws.person.storageservice.com/", wsdlLocation = "https://storageserviceperson.herokuapp.com/ws/storageServicePerson?wsdl")
public class StorageServicePerson
    extends Service
{

    private final static URL STORAGESERVICEPERSON_WSDL_LOCATION;
    private final static WebServiceException STORAGESERVICEPERSON_EXCEPTION;
    private final static QName STORAGESERVICEPERSON_QNAME = new QName("http://ws.person.storageservice.com/", "storageServicePerson");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://storageserviceperson.herokuapp.com/ws/storageServicePerson?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGESERVICEPERSON_WSDL_LOCATION = url;
        STORAGESERVICEPERSON_EXCEPTION = e;
    }

    public StorageServicePerson() {
        super(__getWsdlLocation(), STORAGESERVICEPERSON_QNAME);
    }

    public StorageServicePerson(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGESERVICEPERSON_QNAME, features);
    }

    public StorageServicePerson(URL wsdlLocation) {
        super(wsdlLocation, STORAGESERVICEPERSON_QNAME);
    }

    public StorageServicePerson(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGESERVICEPERSON_QNAME, features);
    }

    public StorageServicePerson(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageServicePerson(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalApiPersonModel
     */
    @WebEndpoint(name = "LocalApiPersonImplPort")
    public LocalApiPersonModel getLocalApiPersonImplPort() {
        return super.getPort(new QName("http://ws.person.storageservice.com/", "LocalApiPersonImplPort"), LocalApiPersonModel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalApiPersonModel
     */
    @WebEndpoint(name = "LocalApiPersonImplPort")
    public LocalApiPersonModel getLocalApiPersonImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.person.storageservice.com/", "LocalApiPersonImplPort"), LocalApiPersonModel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGESERVICEPERSON_EXCEPTION!= null) {
            throw STORAGESERVICEPERSON_EXCEPTION;
        }
        return STORAGESERVICEPERSON_WSDL_LOCATION;
    }

}
