
package com.storageservice.fitbit.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalApiFitBitModel", targetNamespace = "http://ws.fitbit.storageservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalApiFitBitModel {


    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns com.storageservice.fitbit.ws.Goal
     */
    @WebMethod
    @WebResult(name = "dailygoal", targetNamespace = "")
    @RequestWrapper(localName = "getDailyGoal", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetDailyGoal")
    @ResponseWrapper(localName = "getDailyGoalResponse", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetDailyGoalResponse")
    @Action(input = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getDailyGoalRequest", output = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getDailyGoalResponse")
    public Goal getDailyGoal(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns com.storageservice.fitbit.ws.WeightGoal
     */
    @WebMethod
    @WebResult(name = "weightGoal", targetNamespace = "")
    @RequestWrapper(localName = "getWeightGoal", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetWeightGoal")
    @ResponseWrapper(localName = "getWeightGoalResponse", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetWeightGoalResponse")
    @Action(input = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getWeightGoalRequest", output = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getWeightGoalResponse")
    public WeightGoal getWeightGoal(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param startDate
     * @param accessToken
     * @param userId
     * @param endDate
     * @param refreshToken
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "weightDifference", targetNamespace = "")
    @RequestWrapper(localName = "getPeriodWeightDifference", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetPeriodWeightDifference")
    @ResponseWrapper(localName = "getPeriodWeightDifferenceResponse", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetPeriodWeightDifferenceResponse")
    @Action(input = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getPeriodWeightDifferenceRequest", output = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getPeriodWeightDifferenceResponse")
    public double getPeriodWeightDifference(
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns com.storageservice.fitbit.ws.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "getWeightHeight", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetWeightHeight")
    @ResponseWrapper(localName = "getWeightHeightResponse", targetNamespace = "http://ws.fitbit.storageservice.com/", className = "com.storageservice.fitbit.ws.GetWeightHeightResponse")
    @Action(input = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getWeightHeightRequest", output = "http://ws.fitbit.storageservice.com/LocalApiFitBitModel/getWeightHeightResponse")
    public Person getWeightHeight(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

}
